import {
  spfOne,
  spfTwo,
  spfThree,
  spfFour,
  bestSellerOne,
  bestSellerTwo,
  bestSellerThree,
  bestSellerFour,
  newArrOne,
  newArrTwo,
  newArrThree,
  newArrFour,
  imprimante1,
  imprimante2,
  imprimante4,
  imprimante5,
  imprimante6,
  imprimante7,
  imprimante8,
  imprimante9,
  encre1,
  encre2,
  encre3,
  encre4,
  ruban1,
  ruban2,
  ruban3,
  ruban4,
  bac1,
  bac2,
  bac3,
  bac4,
  pdf1,
  IMPRIMANTE_PANTUM_CP2200DW,
  IMPRIMANTE_PANTUM_BM5100FDW,
  IMPRIMANTE_PANTUM_M6609N,
  IMPRIMANTE_PANTUM_P3300DN,
  IMPRIMANTE_PANTUM_P3300DW,
  IMPRIMANTE_PANTUM_P2509W,
  IMPRIMANTE_PANTUM_BP5100DN,
  IMPRIMANTE_PANTUM_M6559N,
  IMPRIMANTE_PANTUM_P2509,
  hp1,
  hp2,
  hp3,
  ricoh1,
  ricoh2,
  ricoh3,
  ricoh4,
  ricoh5,
  espson1,
  espson2,
} from "../assets/images/index";

import "./style.css";

// =================== NavBarList Start here ====================
export const navBarList = [
  {
    _id: 1001,
    title: "Home",
    link: "/",
  },
  {
    _id: 1002,
    title: "Shop",
    link: "/shop",
  },
  {
    _id: 1003,
    title: "About",
    link: "/about",
  },
  {
    _id: 1004,
    title: "Contact",
    link: "contact",
  },
  {
    _id: 1005,
    title: "Journal",
    link: "/journal",
  },
];
// =================== NavBarList End here ======================
// =================== Special Offer data Start here ============
export const SplOfferData = [
  {
    _id: "201",
    img: IMPRIMANTE_PANTUM_CP2200DW,
    productName: "Stringer Denim Jacket",
    price: "440.00",
    color: "Blue",
    badge: true,
    des: "The Stringer Denim Jacket is a timeless piece, offering a rugged yet stylish appeal. Its durable fabric and classic design make it a versatile addition to any wardrobe. Perfect for layering, it pairs effortlessly with both casual and dressy outfits. This jacket is a must-have for those seeking both comfort and fashion.",
    cat: "Denim",
  },
  {
    _id: "202",
    img: IMPRIMANTE_PANTUM_BM5100FDW,
    productName: "imprimante",
    price: "440.00",
    color: "Brown",
    badge: true,
    des: "Luxurious and durable, leather is the epitome of timeless style. The Beem Leather+Woolen Jacket combines classic leather with cozy wool for ultimate comfort. Crafted with precision, this jacket offers a perfect blend of warmth and elegance. Elevate your wardrobe with the sophistication of Beem's premium materials and design.",
    cat: "Leather",
  },
  {
    _id: "203",
    img: IMPRIMANTE_PANTUM_BP5100DN,
    productName: "Prime Black regular fit Leather Jacket",
    price: "440.00",
    color: "Black",
    badge: true,
    des: "The Prime Black regular fit Leather Jacket is a timeless piece, perfect for any wardrobe. Crafted from high-quality leather, it offers both durability and a sleek, stylish appearance. Its regular fit ensures comfort while maintaining a modern silhouette. The jacket features a minimalist design, making it versatile for both casual and semi-formal occasions. With its classic black color, it's an essential staple that can elevate any outfit.",
    cat: "Leather",
  },

  {
    _id: "204",
    img: imprimante7,
    productName: "Gold Bomber Jacket",
    price: "440.00",
    color: "White",
    badge: true,
    des: "The Gold Bomber Jacket is a striking and fashionable outerwear piece, perfect for making a bold statement. Crafted from premium materials, it combines both comfort and durability. The jacket features a classic bomber silhouette with ribbed cuffs, collar, and hem for a snug fit. Its shimmering gold color adds a touch of luxury and glam to any outfit. Ideal for both casual and semi-formal occasions, this jacket effortlessly elevates your style.",
    cat: "Bomber",
  },

  {
    _id: "205",
    img: imprimante6,
    productName: "Slim Fit Denim Stringer Jacket",
    price: "440.00",
    color: "Blue",
    badge: true,
    des: "The Slim Fit Denim Stringer Jacket is a modern take on a classic wardrobe staple. Designed with a sleek, slim fit, it enhances your silhouette while providing a comfortable wear. Made from high-quality denim, this jacket offers both durability and style. The unique stringer details add a contemporary edge, setting it apart from traditional denim jackets. Versatile and chic, it's perfect for layering over casual or smart-casual outfits, making it a must-have for any fashion-forward wardrobe.",
    cat: "Denim",
  },

  {
    _id: "206",
    img: imprimante8,
    productName: "Prime Neon Yellow Jacket without Hood",
    price: "440.00",
    color: "Yellow",
    badge: true,
    des: "The Prime Neon Yellow Jacket without Hood is a standout piece designed for those who love to make a bold statement. Crafted from high-quality materials, it ensures both durability and comfort. Its vibrant neon yellow color grabs attention and adds a pop of brightness to any outfit. The jacket's streamlined design, free of a hood, offers a sleek and modern look. Perfect for both casual and active wear, it combines functionality with a striking aesthetic.",
    cat: "Stringer",
  },

];
// =================== Special Offer data End here ==============

// =================== PaginationItems Start here ===============

export const paginationItems = [
  {
    _id: "201",
    img: IMPRIMANTE_PANTUM_CP2200DW,
    productName: "Stringer Denim Jacket",
    price: "440.00",
    color: "Blue",
    badge: true,
    brand: "Stringer",
    des: "The Stringer Denim Jacket is a timeless piece, offering a rugged yet stylish appeal. Its durable fabric and classic design make it a versatile addition to any wardrobe. Perfect for layering, it pairs effortlessly with both casual and dressy outfits. This jacket is a must-have for those seeking both comfort and fashion.",
    cat: "Denim",
    pdf: pdf1,
    ficheTech: [
    { label: "Material", value: "High-quality denim" },
    { label: "Color", value: "Classic blue" },
    { label: "Fit", value: "Regular fit" },
    { label: "Pockets", value: "Two chest pockets with button flaps" },
    { label: "Closure", value: "Button-front closure" },
    { label: "Collar", value: "Standard collar" },
    { label: "Sleeves", value: "Long sleeves with button cuffs" },
    { label: "Care Instructions", value: "Machine washable" }
    ],

  },
  {
    _id: "202",
    img: IMPRIMANTE_PANTUM_BM5100FDW,
    productName: "Beem Leather+Woolen Jacket",
    price: "440",
    color: "Brown",
    badge: true,
    brand: "Beem",
    des: "Luxurious and durable, leather is the epitome of timeless style. The Beem Leather+Woolen Jacket combines classic leather with cozy wool for ultimate comfort. Crafted with precision, this jacket offers a perfect blend of warmth and elegance. Elevate your wardrobe with the sophistication of Beem's premium materials and design.",
    cat: "Leather",
    pdf: pdf1,
    ficheTech: [
    { label: "Material", value: "Genuine leather" },
    { label: "Color", value: "Classic Brown" },
    { label: "Lining", value: "Polyester lining" },
    { label: "Closure", value: "Zipper front closure" },
    { label: "Pockets", value: "Two side pockets, one internal pocket" },
    { label: "Collar", value: "Stand-up collar with snap button" },
    { label: "Cuffs", value: "Zipper cuffs" },
    { label: "Care Instructions", value: "Dry clean only" },
    { label: "Fit", value: "Slim fit" },
    { label: "Length", value: "Hip-length" },
    { label: "Sleeve Type", value: "Long sleeves" },
    { label: "Ventilation", value: "Underarm ventilation panels" },
    { label: "Reinforcement", value: "Double-stitched seams" },
    { label: "Weight", value: "1.2 kg" }
    ],

  },

  {
    _id: "203",
    img: IMPRIMANTE_PANTUM_BP5100DN,
    productName: "Prime Black regular fit Leather Jacket",
    price: "440",
    color: "Black",
    badge: true,
    brand: "Prime",
    des: "The Prime Black regular fit Leather Jacket is a timeless piece, perfect for any wardrobe. Crafted from high-quality leather, it offers both durability and a sleek, stylish appearance. Its regular fit ensures comfort while maintaining a modern silhouette. The jacket features a minimalist design, making it versatile for both casual and semi-formal occasions. With its classic black color, it's an essential staple that can elevate any outfit.",
    cat: "Leather",
    pdf: pdf1,
    ficheTech: [
    { label: "Material", value: "Genuine leather" },
    { label: "Color", value: "Classic Black" },
    { label: "Lining", value: "Polyester lining" },
    { label: "Closure", value: "Zipper front closure" },
    { label: "Pockets", value: "Two side pockets, one internal pocket" },
    { label: "Collar", value: "Stand-up collar with snap button" },
    { label: "Cuffs", value: "Zipper cuffs" },
    { label: "Care Instructions", value: "Dry clean only" },
    { label: "Fit", value: "Slim fit" },
    { label: "Length", value: "Hip-length" },
    { label: "Sleeve Type", value: "Long sleeves" },
    { label: "Ventilation", value: "Underarm ventilation panels" },
    { label: "Reinforcement", value: "Double-stitched seams" },
    { label: "Weight", value: "1.2 kg" }
    ],
  },

  {
    _id: "204",
    img: imprimante7,
    productName: "Gold Bomber Jacket",
    price: "440",
    color: "White",
    badge: true,
    brand: "Gold",
    des: "The Gold Bomber Jacket is a striking and fashionable outerwear piece, perfect for making a bold statement. Crafted from premium materials, it combines both comfort and durability. The jacket features a classic bomber silhouette with ribbed cuffs, collar, and hem for a snug fit. Its shimmering gold color adds a touch of luxury and glam to any outfit. Ideal for both casual and semi-formal occasions, this jacket effortlessly elevates your style.",
    cat: "Bomber",
    pdf: pdf1,
    ficheTech: [
    { label: "Material", value: "Satin gold fabric" },
    { label: "Color", value: "Gold" },
    { label: "Lining", value: "Polyester lining" },
    { label: "Closure", value: "Zipper front closure" },
    { label: "Pockets", value: "Two side pockets, one internal pocket" },
    { label: "Collar", value: "Ribbed collar" },
    { label: "Cuffs", value: "Ribbed cuffs" },
    { label: "Hem", value: "Ribbed hem" },
    { label: "Care Instructions", value: "Dry clean only" },
    { label: "Fit", value: "Regular fit" },
    { label: "Length", value: "Waist-length" },
    { label: "Sleeve Type", value: "Long sleeves" },
    { label: "Closure Type", value: "Full zip" },
    { label: "Weight", value: "0.8 kg" },
    { label: "Style", value: "Bomber" }
  ],
  },

  {
    _id: "205",
    img: imprimante6,
    productName: "Slim Fit Denim Stringer Jacket",
    price: "440",
    color: "Blue",
    badge: true,
    brand: "Stringer",
    des: "The Gold Bomber Jacket is a striking and fashionable outerwear piece, perfect for making a bold statement. Crafted from premium materials, it combines both comfort and durability. The jacket features a classic bomber silhouette with ribbed cuffs, collar, and hem for a snug fit. Its shimmering gold color adds a touch of luxury and glam to any outfit. Ideal for both casual and semi-formal occasions, this jacket effortlessly elevates your style.",
    cat: "Denim",
    pdf: pdf1,
    ficheTech: [
    { label: "Material", value: "High-quality denim" },
    { label: "Color", value: "Blue" },
    { label: "Lining", value: "Unlined" },
    { label: "Closure", value: "Button-front closure" },
    { label: "Pockets", value: "Two chest pockets with button flaps, two side pockets" },
    { label: "Collar", value: "Classic spread collar" },
    { label: "Cuffs", value: "Button cuffs" },
    { label: "Care Instructions", value: "Machine washable" },
    { label: "Fit", value: "Slim fit" },
    { label: "Length", value: "Hip-length" },
    { label: "Sleeve Type", value: "Long sleeves" },
    { label: "Stitching", value: "Contrast stitching" },
    { label: "Weight", value: "1 kg" },
    { label: "Style", value: "Casual" }
    ],
  },

  {
    _id: "206",
    img: imprimante8,
    productName: "Prime Neon Yellow Jacket without Hood ",
    price: "440",
    color: "Yellow",
    badge: true,
    brand: "Prime",
    des: "The Prime Neon Yellow Jacket without Hood is a standout piece designed for those who love to make a bold statement. Crafted from high-quality materials, it ensures both durability and comfort. Its vibrant neon yellow color grabs attention and adds a pop of brightness to any outfit. The jacket's streamlined design, free of a hood, offers a sleek and modern look. Perfect for both casual and active wear, it combines functionality with a striking aesthetic.",
    cat: "Neon",
    pdf: pdf1,
    ficheTech: [
    { label: "Material", value: "Polyester" },
    { label: "Color", value: "Neon Yellow" },
    { label: "Lining", value: "Mesh lining" },
    { label: "Closure", value: "Zipper front closure" },
    { label: "Pockets", value: "Two side pockets, one internal pocket" },
    { label: "Collar", value: "Stand-up collar" },
    { label: "Cuffs", value: "Elastic cuffs" },
    { label: "Hem", value: "Elastic hem" },
    { label: "Care Instructions", value: "Machine washable" },
    { label: "Fit", value: "Regular fit" },
    { label: "Length", value: "Hip-length" },
    { label: "Sleeve Type", value: "Long sleeves" },
    { label: "Ventilation", value: "Underarm ventilation panels" },
    { label: "Reflective Elements", value: "Reflective strips on sleeves and back" },
    { label: "Weight", value: "0.7 kg" },
    { label: "Style", value: "Sporty" }
    ],
  },
  
];
